# Variables
server_ip: "10.10.88.101"
username: "yuri"
context: "k3s"

#cloud-config
package_upgrade: true
packages:
  - qemu-guest-agent
  - nfs-common
  - linux-modules-extra-5.15.0-1034-generic

timezone: America/Chicago
users:
  - name: <your username>
    passwd: <your password hash>
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - <your ssh public key>

power_state:
    delay: now
    mode: reboot
    message: Rebooting after cloud-init completion
    condition: true

# Perform k3s install on first boot
runcmd:
  - k3sup install --ip ${server_ip} --cluster --context ${k3s} --ssh-key ~/.ssh/id_rsa --user ${username}
